"""Corrected the issue with instructions

Revision ID: a37b491e0756
Revises: f4e5756855fd
Create Date: 2025-06-26 16:00:07.023407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37b491e0756'
down_revision = 'f4e5756855fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.String(), nullable=False))
        batch_op.drop_column('Instructions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Instructions', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
